spring:
  application:
    name: Shipping-Microservice

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3315}/${DB_NAME:mi_basedatos_app}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:user_1}
    password: ${DB_PASSWORD:mi_usUario22}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

google:
  maps:
    api-key: ${GOOGLE_API_KEY:AIzaSyAzX1ma-i25KjrXbIA9TTdoxWRbE975a3I}
    directions-url: https://maps.googleapis.com/maps/api/directions/json
server:
  port: 8090
