spring:
  application:
    name: client-api


  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3320}/${DB_NAME:mi_basedatos_app}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:user_1}
    password: ${DB_PASSWORD:mi_usUario22}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # o 'create', 'none', seg√∫n lo que necesites
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8092

